# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27d801240eb1e196317492d031280569ca24db504b35b85ad95b6e44188572656fb802d40746b9be6d4e3ff7c343eec19d8fb1aeeac1aa3b09a9b19a9fc321c8

test:
  secret_key_base: 6ac15637012029d11ae8b7f991f099e16c0c5dbe23b9514c6e9eaee40a2c4c70b2a9f2ece591bd6370ffa11b7bbaf8931a48bc70ece957907e7fffed2885156f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
